# Generated by Django 2.0.6 on 2018-06-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=100)),
                ('starttime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('user_id', models.UUIDField()),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.UUIDField()),
                ('starter_id', models.UUIDField()),
                ('starter_name', models.CharField(max_length=50)),
                ('target_id', models.UUIDField()),
                ('target_name', models.CharField(max_length=50)),
                ('is_pending', models.BooleanField()),
                ('is_success', models.BooleanField()),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
