# Generated by Django 2.0.6 on 2018-06-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180616_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user_id',
            new_name='owner_user_id',
        ),
    ]
