# Generated by Django 2.0.6 on 2018-06-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180616_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owner_user_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='target_id',
            field=models.PositiveIntegerField(),
        ),
    ]
