# Generated by Django 2.0.6 on 2018-06-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180616_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='starter_id',
            field=models.PositiveIntegerField(),
        ),
    ]
