# Generated by Django 2.0.6 on 2018-06-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180617_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='endtime',
            field=models.DateTimeField(default='2018-6-20'),
            preserve_default=False,
        ),
    ]
