# Generated by Django 2.0.6 on 2018-06-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180618_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='p_color',
            field=models.TextField(default=123, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='s_color',
            field=models.TextField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
